import { motion } from 'framer-motion'
import { clamp } from '../../utils/mockDraftLogic.js'

export function HeroMeta({ label, value, color }) { return <div className="rounded-2xl bg-white/35 px-3 py-3 text-center"><div className="font-mono text-[9px] font-black uppercase tracking-[.18em] text-lo">{label}</div><div className="mt-1 font-mono text-sm font-black" style={{ color }}>{value || '-'}</div></div> }
export function AttributeBar({ label, value, color, featured = false }) { return <div><div className="mb-2 flex justify-between font-mono font-black uppercase tracking-[.14em]"><span className={featured ? 'text-[10px] text-slate-700' : 'text-[8px] text-lo'}>{label}</span><span className={featured ? 'text-[11px] text-slate-800' : 'text-[9px] text-slate-600'}>{Math.round(value)}</span></div><div className={(featured ? 'h-3.5' : 'h-2.5') + ' overflow-hidden rounded-full bg-white/50 shadow-inner'}><motion.div initial={{ width: 0 }} animate={{ width: clamp(value) + '%' }} transition={{ duration: .75, ease: [0.22, 1, 0.36, 1] }} className="h-full rounded-full" style={{ background: color, opacity: featured ? 1 : .72 }} /></div></div> }
export function InfoLine({ label, value, accent }) { return <div className="flex items-center justify-between rounded-2xl bg-white/32 px-3 py-2"><span className="font-mono text-[9px] font-black uppercase tracking-[.16em] text-lo">{label}</span><span className="font-mono text-xs font-black" style={{ color: accent || '#3f3a36' }}>{value}</span></div> }
export function MovementBadge({ movement }) { return <span className="rounded-full px-3 py-1 font-mono text-[9px] font-black uppercase tracking-[.14em]" style={{ background: movement.tone + '18', color: movement.tone }}>{movement.label}</span> }
export function GlassPanel({ children, className = '', style }) { return <div className={'rounded-[34px] border border-white/60 bg-white/48 shadow-[0_8px_30px_rgb(0,0,0,0.04)] backdrop-blur-xl ' + className} style={style}>{children}</div> }
export function PremiumButton({ onClick, color, children, strong }) { return <button onClick={onClick} className="rounded-full px-6 py-3 font-mono text-[10px] font-black uppercase tracking-[.18em] transition-transform hover:-translate-y-0.5 active:scale-95" style={{ background: '#edeae4', color, fontWeight: strong ? 900 : 700, boxShadow: '5px 5px 13px #d4d0ca, -5px -5px 13px #ffffff, inset 0 0 0 1px ' + color + '33' }}>{children}</button> }
export function StatusPill({ children }) { return <div className="rounded-full bg-white/44 px-4 py-2 font-mono text-[10px] font-black uppercase tracking-[.18em] text-muted backdrop-blur-md">{children}</div> }
export function Skeleton({ w = '75%' }) { return <div className="h-2 rounded-full" style={{ width: w, background: '#d8d4ce', animation: 'pulse 1.5s ease infinite' }} /> }
